sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t com777/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true com777/react-test npm run test

after_success:
  - docker build -t com777/multi-client ./client
  - docker build -t com777/multi-nginx ./nginx
  - docker build -t com777/multi-server ./server
  - docker build -t com777/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push com777/multi-client
  - docker push com777/multi-nginx
  - docker push com777/multi-server
  - docker push com777/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-436912966171"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
